beaches_database/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('beaches/', views.beaches_index, name='index'),
    path('beaches/<int:beach_id>/', views.beaches_detail, name='detail'),
    path('beaches/create/', views.BeachCreate.as_view(), name='beaches_create'),
    path('beaches/<int:pk>/update/', views.BeachUpdate.as_view(), name='beaches_update'),
    path('beaches/<int:pk>/delete/', views.BeachDelete.as_view(), name= 'beaches_delete'),
    path('beach/<int:beach_id>/beach_water/', views.add_water, name='add_water'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

TYPE=(
    ('O', 'Ocean'),
    ('L', 'Lake'),
    ('R', 'River')
)
class Beach (models.Model):
    name= models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"beach_id": self.id})

class Water(models.Model):
    visit= models.DateField('visit date')
    type = models.CharField(
        max_length=1,
        choices=TYPE,
        default=TYPE[0][0]
        )
    
    beach = models.ForeignKey(Beach, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_type_display()} on {self.visit}"
    
    class Meta:
        ordering=['-visit']

main_app/forms.py
from django.forms import ModelForm
from .models import Water

class WaterForm(ModelForm):
  class Meta:
    model = Water
    fields = ['visit', 'type']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Beach
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import WaterForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def beaches_index(request):
    beaches= Beach.objects.all()
    return render(request, 'beaches/index.html', {'beaches': beaches}) 

def beaches_detail(request, beach_id):
    beach = Beach.objects.get(id=beach_id)
    water_form=WaterForm()
    return render(request, 'beaches/detail.html', {'beach': beach, 'water_form': water_form})

def add_water(request, beach_id):
  form = WaterForm (request.POST)
  if form.is_valid():
      new_water = form.save(commit=False)
      new_water.beach_id=beach_id
      new_water.save()
  return redirect('detail', beach_id=beach_id)

class BeachCreate(CreateView):
    model=Beach
    fields='__all__'
    success_url='/beaches/'

class BeachUpdate(UpdateView):
    model= Beach
    fields=['name', 'location', 'description']

class BeachDelete(DeleteView):
    model= Beach
    success_url= '/beaches/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}


<h1>About Beaches</h1>
<hr/>
<p>Learn about the beaches from across the world</p>

{% endblock %}

main_app/templates/base.html
 {%  load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Beach Database</title>
  <link rel='stylesheet' type="text/css" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
 
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="brand-logo center">&nbsp;&nbsp;Beaches</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="{% url 'beaches_create' %}">Add a Beach</a></li>
          <li><a href="/beaches">Beaches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Beach Database &nbsp;</div>
  </footer>
   
</body>
</html>

main_app/templates/beaches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ beach.name }} Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ beach.name }}</span>
        <p>Location: {{ cat.location }}</p>
        <p>Description: {{ beach.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'beaches_update' beach.id %}">Edit</a>
        <a href="{% url 'beaches_delete' beach.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_water' beach.id %}" method="post">
        {% csrf_token %}
        {{ water_form.as_p }}
        <input type="submit" class="btn" value="Add Water">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Visit</th><th>Type of Water</th></tr>
      </thead>
      <tbody>
        {% for water in beach.water_set.all %}
          <tr>
            <td>{{water.visit}}</td>
            <td>{{water.get_type_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

   var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/beaches/index.html
 {% extends 'base.html' %}
 {%  load static  %}
 


{% block content%}
<h1> Beaches </h1>
{%for beach in beaches %}
     <div class="row">
    <div class="col s12 m6">
      <div class="card">
        <div class="card-image">
          <img src="https://i.imgur.com/HUqnj6t.png">
          <span class="card-title">{{beach.name}}</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" href='{%url 'detail' beach.id %}'><i class="material-icons">+</i></a>
        </div>
        <div class="card-content">
          <p>Location: {{beach.location}}</p>
          <p>Description: {{beach.description}}</p>
        </div>
      </div>
    </div>
  </div>
{%endfor%}

{%endblock%}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Home Page: Ocean</h1>
{% endblock %}

main_app/templates/main_app/beach_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete a Beach</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' beach.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/beach_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}